-- liquibase formatted sql

-- changeset customer:1
CREATE TABLE customer (id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, birth date NULL, "name" varchar(255) NULL, CONSTRAINT customer_pkey PRIMARY KEY (id))
